In [15]:
import requests
import pandas as pd

## Get in requests

In [67]:
#API do IBGE sobre localidades (Pais, estado, cidades)
url_base = "https://servicodados.ibge.gov.br/api/v1/localidades"

In [57]:
endpoint_paises = url_base+"/paises"

response = requests.get(endpoint_paises)

In [58]:
response.status_code

200

In [59]:
response.json()

[{'id': {'M49': 4, 'ISO-ALPHA-2': 'AF', 'ISO-ALPHA-3': 'AFG'},
  'nome': 'Afeganistão',
  'regiao-intermediaria': None,
  'sub-regiao': {'id': {'M49': 34},
   'nome': 'Ásia meridional (Sul da Ásia)',
   'regiao': {'id': {'M49': 142}, 'nome': 'Ásia'}}},
 {'id': {'M49': 8, 'ISO-ALPHA-2': 'AL', 'ISO-ALPHA-3': 'ALB'},
  'nome': 'Albânia',
  'regiao-intermediaria': None,
  'sub-regiao': {'id': {'M49': 39},
   'nome': 'Europa meridional  (Sul da Europa)',
   'regiao': {'id': {'M49': 150}, 'nome': 'Europa'}}},
 {'id': {'M49': 12, 'ISO-ALPHA-2': 'DZ', 'ISO-ALPHA-3': 'DZA'},
  'nome': 'Argélia',
  'regiao-intermediaria': None,
  'sub-regiao': {'id': {'M49': 15},
   'nome': 'África setentrional (Norte da África)',
   'regiao': {'id': {'M49': 2}, 'nome': 'África'}}},
 {'id': {'M49': 20, 'ISO-ALPHA-2': 'AD', 'ISO-ALPHA-3': 'AND'},
  'nome': 'Andorra',
  'regiao-intermediaria': None,
  'sub-regiao': {'id': {'M49': 39},
   'nome': 'Europa meridional  (Sul da Europa)',
   'regiao': {'id': {'M49': 150}, 'nome': 'Europa'}}},
 {'id': {'M49': 24, 'ISO-ALPHA-2': 'AO', 'ISO-ALPHA-3': 'AGO'},
  'nome': 'Angola',
  'regiao-intermediaria': {'id': {'M49': 17}, 'nome': 'África central'},
  'sub-regiao': {'id': {'M49': 202},
   'nome': 'África subsaariana',
   'regiao': {'id': {'M49': 2}, 'nome': 'África'}}},
 {'id': {'M49': 28, 'ISO-ALPHA-2': 'AG', 'ISO-ALPHA-3': 'ATG'},
  'nome': 'Antígua e Barbuda',
  'regiao-intermediaria': {'id': {'M49': 29}, 'nome': 'Caribe'},
  'sub-regiao': {'id': {'M49': 419},
   'nome': 'América Latina e Caribe',
   'regiao': {'id': {'M49': 19}, 'nome': 'América'}}},
 {'id': {'M49': 31, 'ISO-ALPHA-2': 'AZ', 'ISO-ALPHA-3': 'AZE'},
  'nome': 'Azerbaijão',
  'regiao-intermediaria': None,
  'sub-regiao': {'id': {'M49': 145},
   'nome': 'Ásia ocidental  (Oeste da Ásia)',
   'regiao': {'id': {'M49': 142}, 'nome': 'Ásia'}}},
 {'id': {'M49': 32, 'ISO-ALPHA-2': 'AR', 'ISO-ALPHA-3': 'ARG'},
  'nome': 'Argentina',
  'regiao-intermediaria': {'id': {'M49': 5}, 'nome': 'América do sul'},
  'sub-regiao': {'id': {'M49': 419},
   'nome': 'América Latina e Caribe',
   'regiao': {'id': {'M49': 19}, 'nome': 'América'}}},
 {'id': {'M49': 36, 'ISO-ALPHA-2': 'AU', 'ISO-ALPHA-3': 'AUS'},
  'nome': 'Austrália',
  'regiao-intermediaria': None,
  'sub-regiao': {'id': {'M49': 53},
   'nome': 'Austrália e Nova Zelândia',
   'regiao': {'id': {'M49': 9}, 'nome': 'Oceania'}}},
 {'id': {'M49': 40, 'ISO-ALPHA-2': 'AT', 'ISO-ALPHA-3': 'AUT'},
  'nome': 'Áustria',
  'regiao-intermediaria': None,
  'sub-regiao': {'id': {'M49': 155},
   'nome': 'Europa ocidental (Oeste da Europa)',
   'regiao': {'id': {'M49': 150}, 'nome': 'Europa'}}},
 {'id': {'M49': 44, 'ISO-ALPHA-2': 'BS', 'ISO-ALPHA-3': 'BHS'},
  'nome': 'Bahamas',
  'regiao-intermediaria': {'id': {'M49': 29}, 'nome': 'Caribe'},
  'sub-regiao': {'id': {'M49': 419},
   'nome': 'América Latina e Caribe',
   'regiao': {'id': {'M49': 19}, 'nome': 'América'}}},
 {'id': {'M49': 48, 'ISO-ALPHA-2': 'BH', 'ISO-ALPHA-3': 'BHR'},
  'nome': 'Barein',
  'regiao-intermediaria': None,
  'sub-regiao': {'id': {'M49': 145},
   'nome': 'Ásia ocidental  (Oeste da Ásia)',
   'regiao': {'id': {'M49': 142}, 'nome': 'Ásia'}}},
 {'id': {'M49': 50, 'ISO-ALPHA-2': 'BD', 'ISO-ALPHA-3': 'BGD'},
  'nome': 'Bangladesh',
  'regiao-intermediaria': None,
  'sub-regiao': {'id': {'M49': 34},
   'nome': 'Ásia meridional (Sul da Ásia)',
   'regiao': {'id': {'M49': 142}, 'nome': 'Ásia'}}},
 {'id': {'M49': 51, 'ISO-ALPHA-2': 'AM', 'ISO-ALPHA-3': 'ARM'},
  'nome': 'Armênia',
  'regiao-intermediaria': None,
  'sub-regiao': {'id': {'M49': 145},
   'nome': 'Ásia ocidental  (Oeste da Ásia)',
   'regiao': {'id': {'M49': 142}, 'nome': 'Ásia'}}},
 {'id': {'M49': 52, 'ISO-ALPHA-2': 'BB', 'ISO-ALPHA-3': 'BRB'},
  'nome': 'Barbados',
  'regiao-intermediaria': {'id': {'M49': 29}, 'nome': 'Caribe'},
  'sub-regiao': {'id': {'M49': 419},
   'nome': 'América Latina e Caribe',
   'regiao': {'id': {'M49': 19}, 'nome': 'América'}}},
 {'id': {'M49': 56, 'ISO-ALPHA-2': 'BE', 'ISO-ALPHA-3': 'BEL'},
  'nome': 'Bélgica',
  'regiao-intermediaria': None,
  'sub-regiao': {'id': {'M49': 155},
   'nome': 'Europa ocidental (Oeste da Europa)',
   'regiao': {'id': {'M49': 150}, 'nome': 'Europa'}}},
 {'id': {'M49': 64, 'ISO-ALPHA-2': 'BT', 'ISO-ALPHA-3': 'BTN'},
  'nome': 'Butão',
  'regiao-intermediaria': None,
  'sub-regiao': {'id': {'M49': 34},
   'nome': 'Ásia meridional (Sul da Ásia)',
   'regiao': {'id': {'M49': 142}, 'nome': 'Ásia'}}},
 {'id': {'M49': 68, 'ISO-ALPHA-2': 'BO', 'ISO-ALPHA-3': 'BOL'},
  'nome': 'Bolívia',
  'regiao-intermediaria': {'id': {'M49': 5}, 'nome': 'América do sul'},
  'sub-regiao': {'id': {'M49': 419},
   'nome': 'América Latina e Caribe',
   'regiao': {'id': {'M49': 19}, 'nome': 'América'}}},
 {'id': {'M49': 70, 'ISO-ALPHA-2': 'BA', 'ISO-ALPHA-3': 'BIH'},
  'nome': 'Bósnia e Herzegovina',
  'regiao-intermediaria': None,
  'sub-regiao': {'id': {'M49': 39},
   'nome': 'Europa meridional  (Sul da Europa)',
   'regiao': {'id': {'M49': 150}, 'nome': 'Europa'}}},
 {'id': {'M49': 72, 'ISO-ALPHA-2': 'BW', 'ISO-ALPHA-3': 'BWA'},
  'nome': 'Botsuana',
  'regiao-intermediaria': {'id': {'M49': 18},
   'nome': 'África meridional (Sul da África)'},
  'sub-regiao': {'id': {'M49': 202},
   'nome': 'África subsaariana',
   'regiao': {'id': {'M49': 2}, 'nome': 'África'}}},
 {'id': {'M49': 76, 'ISO-ALPHA-2': 'BR', 'ISO-ALPHA-3': 'BRA'},
  'nome': 'Brasil',
  'regiao-intermediaria': {'id': {'M49': 5}, 'nome': 'América do sul'},
  'sub-regiao': {'id': {'M49': 419},
   'nome': 'América Latina e Caribe',
   'regiao': {'id': {'M49': 19}, 'nome': 'América'}}},
 {'id': {'M49': 84, 'ISO-ALPHA-2': 'BZ', 'ISO-ALPHA-3': 'BLZ'},
  'nome': 'Belize',
  'regiao-intermediaria': {'id': {'M49': 13}, 'nome': 'América central'},
  'sub-regiao': {'id': {'M49': 419},
   'nome': 'América Latina e Caribe',
   'regiao': {'id': {'M49': 19}, 'nome': 'América'}}},
 {'id': {'M49': 90, 'ISO-ALPHA-2': 'SB', 'ISO-ALPHA-3': 'SLB'},
  'nome': 'Ilhas Salomão',
  'regiao-intermediaria': None,
  'sub-regiao': {'id': {'M49': 54},
   'nome': 'Melanésia',
   'regiao': {'id': {'M49': 9}, 'nome': 'Oceania'}}},
 {'id': {'M49': 96, 'ISO-ALPHA-2': 'BN', 'ISO-ALPHA-3': 'BRN'},
  'nome': 'Brunei',
  'regiao-intermediaria': None,
  'sub-regiao': {'id': {'M49': 35},
   'nome': 'Sudeste da Ásia',
   'regiao': {'id': {'M49': 142}, 'nome': 'Ásia'}}},
 {'id': {'M49': 100, 'ISO-ALPHA-2': 'BG', 'ISO-ALPHA-3': 'BGR'},
  'nome': 'Bulgária',
  'regiao-intermediaria': None,
  'sub-regiao': {'id': {'M49': 151},
   'nome': 'Europa oriental (Leste da Europa)',
   'regiao': {'id': {'M49': 150}, 'nome': 'Europa'}}},
 {'id': {'M49': 104, 'ISO-ALPHA-2': 'MM', 'ISO-ALPHA-3': 'MMR'},
  'nome': 'Mianmar',
  'regiao-intermediaria': None,
  'sub-regiao': {'id': {'M49': 35},
   'nome': 'Sudeste da Ásia',
   'regiao': {'id': {'M49': 142}, 'nome': 'Ásia'}}},
 {'id': {'M49': 108, 'ISO-ALPHA-2': 'BI', 'ISO-ALPHA-3': 'BDI'},
  'nome': 'Burundi',
  'regiao-intermediaria': {'id': {'M49': 14},
   'nome': 'África oriental (Leste da África)'},
  'sub-regiao': {'id': {'M49': 202},
   'nome': 'África subsaariana',
   'regiao': {'id': {'M49': 2}, 'nome': 'África'}}},
 {'id': {'M49': 112, 'ISO-ALPHA-2': 'BY', 'ISO-ALPHA-3': 'BLR'},
  'nome': 'Belarus',
  'regiao-intermediaria': None,
  'sub-regiao': {'id': {'M49': 151},
   'nome': 'Europa oriental (Leste da Europa)',
   'regiao': {'id': {'M49': 150}, 'nome': 'Europa'}}},
 {'id': {'M49': 116, 'ISO-ALPHA-2': 'KH', 'ISO-ALPHA-3': 'KHM'},
  'nome': 'Camboja',
  'regiao-intermediaria': None,
  'sub-regiao': {'id': {'M49': 35},
   'nome': 'Sudeste da Ásia',
   'regiao': {'id': {'M49': 142}, 'nome': 'Ásia'}}},
 {'id': {'M49': 120, 'ISO-ALPHA-2': 'CM', 'ISO-ALPHA-3': 'CMR'},
  'nome': 'Camarões',
  'regiao-intermediaria': {'id': {'M49': 17}, 'nome': 'África central'},
  'sub-regiao': {'id': {'M49': 202},
   'nome': 'África subsaariana',
   'regiao': {'id': {'M49': 2}, 'nome': 'África'}}},
 {'id': {'M49': 124, 'ISO-ALPHA-2': 'CA', 'ISO-ALPHA-3': 'CAN'},
  'nome': 'Canadá',
  'regiao-intermediaria': None,
  'sub-regiao': {'id': {'M49': 21},
   'nome': 'América do Norte',
   'regiao': {'id': {'M49': 19}, 'nome': 'América'}}},
 {'id': {'M49': 132, 'ISO-ALPHA-2': 'CV', 'ISO-ALPHA-3': 'CPV'},
  'nome': 'Cabo Verde',
  'regiao-intermediaria': {'id': {'M49': 11},
   'nome': 'África ocidental (Oeste da África)'},
  'sub-regiao': {'id': {'M49': 202},
   'nome': 'África subsaariana',
   'regiao': {'id': {'M49': 2}, 'nome': 'África'}}},
 {'id': {'M49': 140, 'ISO-ALPHA-2': 'CF', 'ISO-ALPHA-3': 'CAF'},
  'nome': 'República Centro-Africana',
  'regiao-intermediaria': {'id': {'M49': 17}, 'nome': 'África central'},
  'sub-regiao': {'id': {'M49': 202},
   'nome': 'África subsaariana',
   'regiao': {'id': {'M49': 2}, 'nome': 'África'}}},
 {'id': {'M49': 144, 'ISO-ALPHA-2': 'LK', 'ISO-ALPHA-3': 'LKA'},
  'nome': 'Sri Lanka',
  'regiao-intermediaria': None,
  'sub-regiao': {'id': {'M49': 34},
   'nome': 'Ásia meridional (Sul da Ásia)',
   'regiao': {'id': {'M49': 142}, 'nome': 'Ásia'}}},
 {'id': {'M49': 148, 'ISO-ALPHA-2': 'TD', 'ISO-ALPHA-3': 'TCD'},
  'nome': 'Chade',
  'regiao-intermediaria': {'id': {'M49': 17}, 'nome': 'África central'},
  'sub-regiao': {'id': {'M49': 202},
   'nome': 'África subsaariana',
   'regiao': {'id': {'M49': 2}, 'nome': 'África'}}},
 {'id': {'M49': 152, 'ISO-ALPHA-2': 'CL', 'ISO-ALPHA-3': 'CHL'},
  'nome': 'Chile',
  'regiao-intermediaria': {'id': {'M49': 5}, 'nome': 'América do sul'},
  'sub-regiao': {'id': {'M49': 419},
   'nome': 'América Latina e Caribe',
   'regiao': {'id': {'M49': 19}, 'nome': 'América'}}},
 {'id': {'M49': 156, 'ISO-ALPHA-2': 'CN', 'ISO-ALPHA-3': 'CHN'},
  'nome': 'China',
  'regiao-intermediaria': None,
  'sub-regiao': {'id': {'M49': 30},
   'nome': 'Ásia oriental (Leste da Ásia)',
   'regiao': {'id': {'M49': 142}, 'nome': 'Ásia'}}},
 {'id': {'M49': 170, 'ISO-ALPHA-2': 'CO', 'ISO-ALPHA-3': 'COL'},
  'nome': 'Colômbia',
  'regiao-intermediaria': {'id': {'M49': 5}, 'nome': 'América do sul'},
  'sub-regiao': {'id': {'M49': 419},
   'nome': 'América Latina e Caribe',
   'regiao': {'id': {'M49': 19}, 'nome': 'América'}}},
 {'id': {'M49': 174, 'ISO-ALPHA-2': 'KM', 'ISO-ALPHA-3': 'COM'},
  'nome': 'Comores',
  'regiao-intermediaria': {'id': {'M49': 14},
   'nome': 'África oriental (Leste da África)'},
  'sub-regiao': {'id': {'M49': 202},
   'nome': 'África subsaariana',
   'regiao': {'id': {'M49': 2}, 'nome': 'África'}}},
 {'id': {'M49': 178, 'ISO-ALPHA-2': 'CG', 'ISO-ALPHA-3': 'COG'},
  'nome': 'República do Congo',
  'regiao-intermediaria': {'id': {'M49': 17}, 'nome': 'África central'},
  'sub-regiao': {'id': {'M49': 202},
   'nome': 'África subsaariana',
   'regiao': {'id': {'M49': 2}, 'nome': 'África'}}},
 {'id': {'M49': 180, 'ISO-ALPHA-2': 'CD', 'ISO-ALPHA-3': 'COD'},
  'nome': 'República Democrática do Congo',
  'regiao-intermediaria': {'id': {'M49': 17}, 'nome': 'África central'},
  'sub-regiao': {'id': {'M49': 202},
   'nome': 'África subsaariana',
   'regiao': {'id': {'M49': 2}, 'nome': 'África'}}},
 {'id': {'M49': 188, 'ISO-ALPHA-2': 'CR', 'ISO-ALPHA-3': 'CRI'},
  'nome': 'Costa Rica',
  'regiao-intermediaria': {'id': {'M49': 13}, 'nome': 'América central'},
  'sub-regiao': {'id': {'M49': 419},
   'nome': 'América Latina e Caribe',
   'regiao': {'id': {'M49': 19}, 'nome': 'América'}}},
 {'id': {'M49': 191, 'ISO-ALPHA-2': 'HR', 'ISO-ALPHA-3': 'HRV'},
  'nome': 'Croácia',
  'regiao-intermediaria': None,
  'sub-regiao': {'id': {'M49': 39},
   'nome': 'Europa meridional  (Sul da Europa)',
   'regiao': {'id': {'M49': 150}, 'nome': 'Europa'}}},
 {'id': {'M49': 192, 'ISO-ALPHA-2': 'CU', 'ISO-ALPHA-3': 'CUB'},
  'nome': 'Cuba',
  'regiao-intermediaria': {'id': {'M49': 29}, 'nome': 'Caribe'},
  'sub-regiao': {'id': {'M49': 419},
   'nome': 'América Latina e Caribe',
   'regiao': {'id': {'M49': 19}, 'nome': 'América'}}},
 {'id': {'M49': 196, 'ISO-ALPHA-2': 'CY', 'ISO-ALPHA-3': 'CYP'},
  'nome': 'Chipre',
  'regiao-intermediaria': None,
  'sub-regiao': {'id': {'M49': 145},
   'nome': 'Ásia ocidental  (Oeste da Ásia)',
   'regiao': {'id': {'M49': 142}, 'nome': 'Ásia'}}},
 {'id': {'M49': 203, 'ISO-ALPHA-2': 'CZ', 'ISO-ALPHA-3': 'CZE'},
  'nome': 'República Tcheca',
  'regiao-intermediaria': None,
  'sub-regiao': {'id': {'M49': 151},
   'nome': 'Europa oriental (Leste da Europa)',
   'regiao': {'id': {'M49': 150}, 'nome': 'Europa'}}},
 {'id': {'M49': 204, 'ISO-ALPHA-2': 'BJ', 'ISO-ALPHA-3': 'BEN'},
  'nome': 'Benin',
  'regiao-intermediaria': {'id': {'M49': 11},
   'nome': 'África ocidental (Oeste da África)'},
  'sub-regiao': {'id': {'M49': 202},
   'nome': 'África subsaariana',
   'regiao': {'id': {'M49': 2}, 'nome': 'África'}}},
 {'id': {'M49': 208, 'ISO-ALPHA-2': 'DK', 'ISO-ALPHA-3': 'DNK'},
  'nome': 'Dinamarca',
  'regiao-intermediaria': None,
  'sub-regiao': {'id': {'M49': 154},
   'nome': 'Europa setentrional (Norte da Europa)',
   'regiao': {'id': {'M49': 150}, 'nome': 'Europa'}}},
 {'id': {'M49': 212, 'ISO-ALPHA-2': 'DM', 'ISO-ALPHA-3': 'DMA'},
  'nome': 'Dominica',
  'regiao-intermediaria': {'id': {'M49': 29}, 'nome': 'Caribe'},
  'sub-regiao': {'id': {'M49': 419},
   'nome': 'América Latina e Caribe',
   'regiao': {'id': {'M49': 19}, 'nome': 'América'}}},
 {'id': {'M49': 214, 'ISO-ALPHA-2': 'DO', 'ISO-ALPHA-3': 'DOM'},
  'nome': 'República Dominicana',
  'regiao-intermediaria': {'id': {'M49': 29}, 'nome': 'Caribe'},
  'sub-regiao': {'id': {'M49': 419},
   'nome': 'América Latina e Caribe',
   'regiao': {'id': {'M49': 19}, 'nome': 'América'}}},
 {'id': {'M49': 218, 'ISO-ALPHA-2': 'EC', 'ISO-ALPHA-3': 'ECU'},
  'nome': 'Equador',
  'regiao-intermediaria': {'id': {'M49': 5}, 'nome': 'América do sul'},
  'sub-regiao': {'id': {'M49': 419},
   'nome': 'América Latina e Caribe',
   'regiao': {'id': {'M49': 19}, 'nome': 'América'}}},
 {'id': {'M49': 222, 'ISO-ALPHA-2': 'SV', 'ISO-ALPHA-3': 'SLV'},
  'nome': 'El Salvador',
  'regiao-intermediaria': {'id': {'M49': 13}, 'nome': 'América central'},
  'sub-regiao': {'id': {'M49': 419},
   'nome': 'América Latina e Caribe',
   'regiao': {'id': {'M49': 19}, 'nome': 'América'}}},
 {'id': {'M49': 226, 'ISO-ALPHA-2': 'GQ', 'ISO-ALPHA-3': 'GNQ'},
  'nome': 'Guiné Equatorial',
  'regiao-intermediaria': {'id': {'M49': 17}, 'nome': 'África central'},
  'sub-regiao': {'id': {'M49': 202},
   'nome': 'África subsaariana',
   'regiao': {'id': {'M49': 2}, 'nome': 'África'}}},
 {'id': {'M49': 231, 'ISO-ALPHA-2': 'ET', 'ISO-ALPHA-3': 'ETH'},
  'nome': 'Etiópia',
  'regiao-intermediaria': {'id': {'M49': 14},
   'nome': 'África oriental (Leste da África)'},
  'sub-regiao': {'id': {'M49': 202},
   'nome': 'África subsaariana',
   'regiao': {'id': {'M49': 2}, 'nome': 'África'}}},
 {'id': {'M49': 232, 'ISO-ALPHA-2': 'ER', 'ISO-ALPHA-3': 'ERI'},
  'nome': 'Eritreia',
  'regiao-intermediaria': {'id': {'M49': 14},
   'nome': 'África oriental (Leste da África)'},
  'sub-regiao': {'id': {'M49': 202},
   'nome': 'África subsaariana',
   'regiao': {'id': {'M49': 2}, 'nome': 'África'}}},
 {'id': {'M49': 233, 'ISO-ALPHA-2': 'EE', 'ISO-ALPHA-3': 'EST'},
  'nome': 'Estônia',
  'regiao-intermediaria': None,
  'sub-regiao': {'id': {'M49': 154},
   'nome': 'Europa setentrional (Norte da Europa)',
   'regiao': {'id': {'M49': 150}, 'nome': 'Europa'}}},
 {'id': {'M49': 242, 'ISO-ALPHA-2': 'FJ', 'ISO-ALPHA-3': 'FJI'},
  'nome': 'Fiji',
  'regiao-intermediaria': None,
  'sub-regiao': {'id': {'M49': 54},
   'nome': 'Melanésia',
   'regiao': {'id': {'M49': 9}, 'nome': 'Oceania'}}},
 {'id': {'M49': 246, 'ISO-ALPHA-2': 'FI', 'ISO-ALPHA-3': 'FIN'},
  'nome': 'Finlândia',
  'regiao-intermediaria': None,
  'sub-regiao': {'id': {'M49': 154},
   'nome': 'Europa setentrional (Norte da Europa)',
   'regiao': {'id': {'M49': 150}, 'nome': 'Europa'}}},
 {'id': {'M49': 250, 'ISO-ALPHA-2': 'FR', 'ISO-ALPHA-3': 'FRA'},
  'nome': 'França',
  'regiao-intermediaria': None,
  'sub-regiao': {'id': {'M49': 155},
   'nome': 'Europa ocidental (Oeste da Europa)',
   'regiao': {'id': {'M49': 150}, 'nome': 'Europa'}}},
 {'id': {'M49': 262, 'ISO-ALPHA-2': 'DJ', 'ISO-ALPHA-3': 'DJI'},
  'nome': 'Djibouti',
  'regiao-intermediaria': {'id': {'M49': 14},
   'nome': 'África oriental (Leste da África)'},
  'sub-regiao': {'id': {'M49': 202},
   'nome': 'África subsaariana',
   'regiao': {'id': {'M49': 2}, 'nome': 'África'}}},
 {'id': {'M49': 266, 'ISO-ALPHA-2': 'GA', 'ISO-ALPHA-3': 'GAB'},
  'nome': 'Gabão',
  'regiao-intermediaria': {'id': {'M49': 17}, 'nome': 'África central'},
  'sub-regiao': {'id': {'M49': 202},
   'nome': 'África subsaariana',
   'regiao': {'id': {'M49': 2}, 'nome': 'África'}}},
 {'id': {'M49': 268, 'ISO-ALPHA-2': 'GE', 'ISO-ALPHA-3': 'GEO'},
  'nome': 'Geórgia',
  'regiao-intermediaria': None,
  'sub-regiao': {'id': {'M49': 145},
   'nome': 'Ásia ocidental  (Oeste da Ásia)',
   'regiao': {'id': {'M49': 142}, 'nome': 'Ásia'}}},
 {'id': {'M49': 270, 'ISO-ALPHA-2': 'GM', 'ISO-ALPHA-3': 'GMB'},
  'nome': 'Gâmbia',
  'regiao-intermediaria': {'id': {'M49': 11},
   'nome': 'África ocidental (Oeste da África)'},
  'sub-regiao': {'id': {'M49': 202},
   'nome': 'África subsaariana',
   'regiao': {'id': {'M49': 2}, 'nome': 'África'}}},
 {'id': {'M49': 276, 'ISO-ALPHA-2': 'DE', 'ISO-ALPHA-3': 'DEU'},
  'nome': 'Alemanha',
  'regiao-intermediaria': None,
  'sub-regiao': {'id': {'M49': 155},
   'nome': 'Europa ocidental (Oeste da Europa)',
   'regiao': {'id': {'M49': 150}, 'nome': 'Europa'}}},
 {'id': {'M49': 288, 'ISO-ALPHA-2': 'GH', 'ISO-ALPHA-3': 'GHA'},
  'nome': 'Gana',
  'regiao-intermediaria': {'id': {'M49': 11},
   'nome': 'África ocidental (Oeste da África)'},
  'sub-regiao': {'id': {'M49': 202},
   'nome': 'África subsaariana',
   'regiao': {'id': {'M49': 2}, 'nome': 'África'}}},
 {'id': {'M49': 296, 'ISO-ALPHA-2': 'KI', 'ISO-ALPHA-3': 'KIR'},
  'nome': 'Kiribati',
  'regiao-intermediaria': None,
  'sub-regiao': {'id': {'M49': 57},
   'nome': 'Micronésia',
   'regiao': {'id': {'M49': 9}, 'nome': 'Oceania'}}},
 {'id': {'M49': 300, 'ISO-ALPHA-2': 'GR', 'ISO-ALPHA-3': 'GRC'},
  'nome': 'Grécia',
  'regiao-intermediaria': None,
  'sub-regiao': {'id': {'M49': 39},
   'nome': 'Europa meridional  (Sul da Europa)',
   'regiao': {'id': {'M49': 150}, 'nome': 'Europa'}}},
 {'id': {'M49': 308, 'ISO-ALPHA-2': 'GD', 'ISO-ALPHA-3': 'GRD'},
  'nome': 'Granada',
  'regiao-intermediaria': {'id': {'M49': 29}, 'nome': 'Caribe'},
  'sub-regiao': {'id': {'M49': 419},
   'nome': 'América Latina e Caribe',
   'regiao': {'id': {'M49': 19}, 'nome': 'América'}}},
 {'id': {'M49': 320, 'ISO-ALPHA-2': 'GT', 'ISO-ALPHA-3': 'GTM'},
  'nome': 'Guatemala',
  'regiao-intermediaria': {'id': {'M49': 13}, 'nome': 'América central'},
  'sub-regiao': {'id': {'M49': 419},
   'nome': 'América Latina e Caribe',
   'regiao': {'id': {'M49': 19}, 'nome': 'América'}}},
 {'id': {'M49': 324, 'ISO-ALPHA-2': 'GN', 'ISO-ALPHA-3': 'GIN'},
  'nome': 'Guiné',
  'regiao-intermediaria': {'id': {'M49': 11},
   'nome': 'África ocidental (Oeste da África)'},
  'sub-regiao': {'id': {'M49': 202},
   'nome': 'África subsaariana',
   'regiao': {'id': {'M49': 2}, 'nome': 'África'}}},
 {'id': {'M49': 328, 'ISO-ALPHA-2': 'GY', 'ISO-ALPHA-3': 'GUY'},
  'nome': 'Guiana',
  'regiao-intermediaria': {'id': {'M49': 5}, 'nome': 'América do sul'},
  'sub-regiao': {'id': {'M49': 419},
   'nome': 'América Latina e Caribe',
   'regiao': {'id': {'M49': 19}, 'nome': 'América'}}},
 {'id': {'M49': 332, 'ISO-ALPHA-2': 'HT', 'ISO-ALPHA-3': 'HTI'},
  'nome': 'Haiti',
  'regiao-intermediaria': {'id': {'M49': 29}, 'nome': 'Caribe'},
  'sub-regiao': {'id': {'M49': 419},
   'nome': 'América Latina e Caribe',
   'regiao': {'id': {'M49': 19}, 'nome': 'América'}}},
 {'id': {'M49': 340, 'ISO-ALPHA-2': 'HN', 'ISO-ALPHA-3': 'HND'},
  'nome': 'Honduras',
  'regiao-intermediaria': {'id': {'M49': 13}, 'nome': 'América central'},
  'sub-regiao': {'id': {'M49': 419},
   'nome': 'América Latina e Caribe',
   'regiao': {'id': {'M49': 19}, 'nome': 'América'}}},

In [60]:
df_paises = pd.json_normalize(response.json(), max_level = 0)
df_paises

,id,nome,regiao-intermediaria,sub-regiao
0,"{'M49': 4, 'ISO-ALPHA-2': 'AF', 'ISO-ALPHA-3':...",Afeganistão,None,"{'id': {'M49': 34}, 'nome': 'Ásia meridional (..."
1,"{'M49': 8, 'ISO-ALPHA-2': 'AL', 'ISO-ALPHA-3':...",Albânia,None,"{'id': {'M49': 39}, 'nome': 'Europa meridional..."
2,"{'M49': 12, 'ISO-ALPHA-2': 'DZ', 'ISO-ALPHA-3'...",Argélia,None,"{'id': {'M49': 15}, 'nome': 'África setentrion..."
3,"{'M49': 20, 'ISO-ALPHA-2': 'AD', 'ISO-ALPHA-3'...",Andorra,None,"{'id': {'M49': 39}, 'nome': 'Europa meridional..."
4,"{'M49': 24, 'ISO-ALPHA-2': 'AO', 'ISO-ALPHA-3'...",Angola,"{'id': {'M49': 17}, 'nome': 'África central'}","{'id': {'M49': 202}, 'nome': 'África subsaaria..."
...,...,...,...,...
188,"{'M49': 860, 'ISO-ALPHA-2': 'UZ', 'ISO-ALPHA-3...",Uzbequistão,None,"{'id': {'M49': 143}, 'nome': 'Ásia central', '..."
189,"{'M49': 862, 'ISO-ALPHA-2': 'VE', 'ISO-ALPHA-3...",Venezuela,"{'id': {'M49': 5}, 'nome': 'América do sul'}","{'id': {'M49': 419}, 'nome': 'América Latina e..."
190,"{'M49': 882, 'ISO-ALPHA-2': 'WS', 'ISO-ALPHA-3...",Samoa,None,"{'id': {'M49': 61}, 'nome': 'Polinésia', 'regi..."
191,"{'M49': 887, 'ISO-ALPHA-2': 'YE', 'ISO-ALPHA-3...",Iêmen,None,"{'id': {'M49': 145}, 'nome': 'Ásia ocidental ..."
192,"{'M49': 894, 'ISO-ALPHA-2': 'ZM', 'ISO-ALPHA-3...",Zâmbia,"{'id': {'M49': 14}, 'nome': 'África oriental (...","{'id': {'M49': 202}, 'nome': 'África subsaaria..."

In [61]:
endpoint_estados = url_base+"/estados"

response = requests.get(endpoint_estados)

In [63]:
pd.json_normalize(response.json(), max_level=0)

,id,sigla,nome,regiao
0,11,RO,Rondônia,"{'id': 1, 'sigla': 'N', 'nome': 'Norte'}"
1,12,AC,Acre,"{'id': 1, 'sigla': 'N', 'nome': 'Norte'}"
2,13,AM,Amazonas,"{'id': 1, 'sigla': 'N', 'nome': 'Norte'}"
3,14,RR,Roraima,"{'id': 1, 'sigla': 'N', 'nome': 'Norte'}"
4,15,PA,Pará,"{'id': 1, 'sigla': 'N', 'nome': 'Norte'}"
5,16,AP,Amapá,"{'id': 1, 'sigla': 'N', 'nome': 'Norte'}"
6,17,TO,Tocantins,"{'id': 1, 'sigla': 'N', 'nome': 'Norte'}"
7,21,MA,Maranhão,"{'id': 2, 'sigla': 'NE', 'nome': 'Nordeste'}"
8,22,PI,Piauí,"{'id': 2, 'sigla': 'NE', 'nome': 'Nordeste'}"
9,23,CE,Ceará,"{'id': 2, 'sigla': 'NE', 'nome': 'Nordeste'}"
10,24,RN,Rio Grande do Norte,"{'id': 2, 'sigla': 'NE', 'nome': 'Nordeste'}"
11,25,PB,Paraíba,"{'id': 2, 'sigla': 'NE', 'nome': 'Nordeste'}"
12,26,PE,Pernambuco,"{'id': 2, 'sigla': 'NE', 'nome': 'Nordeste'}"
13,27,AL,Alagoas,"{'id': 2, 'sigla': 'NE', 'nome': 'Nordeste'}"
14,28,SE,Sergipe,"{'id': 2, 'sigla': 'NE', 'nome': 'Nordeste'}"
15,29,BA,Bahia,"{'id': 2, 'sigla': 'NE', 'nome': 'Nordeste'}"
16,31,MG,Minas Gerais,"{'id': 3, 'sigla': 'SE', 'nome': 'Sudeste'}"
17,32,ES,Espírito Santo,"{'id': 3, 'sigla': 'SE', 'nome': 'Sudeste'}"
18,33,RJ,Rio de Janeiro,"{'id': 3, 'sigla': 'SE', 'nome': 'Sudeste'}"
19,35,SP,São Paulo,"{'id': 3, 'sigla': 'SE', 'nome': 'Sudeste'}"
20,41,PR,Paraná,"{'id': 4, 'sigla': 'S', 'nome': 'Sul'}"
21,42,SC,Santa Catarina,"{'id': 4, 'sigla': 'S', 'nome': 'Sul'}"
22,43,RS,Rio Grande do Sul,"{'id': 4, 'sigla': 'S', 'nome': 'Sul'}"
23,50,MS,Mato Grosso do Sul,"{'id': 5, 'sigla': 'CO', 'nome': 'Centro-Oeste'}"
24,51,MT,Mato Grosso,"{'id': 5, 'sigla': 'CO', 'nome': 'Centro-Oeste'}"
25,52,GO,Goiás,"{'id': 5, 'sigla': 'CO', 'nome': 'Centro-Oeste'}"
26,53,DF,Distrito Federal,"{'id': 5, 'sigla': 'CO', 'nome': 'Centro-Oeste'}"

In [64]:
#https://servicodados.ibge.gov.br/api/v1/localidades/estados/{UF}/municipios

endpoint_municipios_ceara = url_base+"/estados/23/municipios"

response = requests.get(endpoint_municipios_ceara)

In [65]:
df_municipios_ceara = pd.json_normalize(response.json(), max_level=0)
df_municipios_ceara

,id,nome,microrregiao,regiao-imediata
0,2300101,Abaiara,"{'id': 23033, 'nome': 'Brejo Santo', 'mesorreg...","{'id': 230012, 'nome': 'Brejo Santo', 'regiao-..."
1,2300150,Acarape,"{'id': 23013, 'nome': 'Baturité', 'mesorregiao...","{'id': 230003, 'nome': 'Redenção-Acarape', 're..."
2,2300200,Acaraú,"{'id': 23001, 'nome': 'Litoral de Camocim e Ac...","{'id': 230017, 'nome': 'Acaraú', 'regiao-inter..."
3,2300309,Acopiara,"{'id': 23021, 'nome': 'Sertão de Senador Pompe...","{'id': 230009, 'nome': 'Iguatu', 'regiao-inter..."
4,2300408,Aiuaba,"{'id': 23020, 'nome': 'Sertão de Inhamuns', 'm...","{'id': 230011, 'nome': 'Juazeiro do Norte', 'r..."
...,...,...,...,...
179,2313807,Uruburetama,"{'id': 23010, 'nome': 'Uruburetama', 'mesorreg...","{'id': 230002, 'nome': 'Itapipoca', 'regiao-in..."
180,2313906,Uruoca,"{'id': 23003, 'nome': 'Coreaú', 'mesorregiao':...","{'id': 230015, 'nome': 'Sobral', 'regiao-inter..."
181,2313955,Varjota,"{'id': 23006, 'nome': 'Ipu', 'mesorregiao': {'...","{'id': 230015, 'nome': 'Sobral', 'regiao-inter..."
182,2314003,Várzea Alegre,"{'id': 23027, 'nome': 'Várzea Alegre', 'mesorr...","{'id': 230011, 'nome': 'Juazeiro do Norte', 'r..."
183,2314102,Viçosa do Ceará,"{'id': 23002, 'nome': 'Ibiapaba', 'mesorregiao...","{'id': 230016, 'nome': 'São Benedito - Ipu - G..."

In [66]:
df_municipios_ceara[df_municipios_ceara['nome'] == 'Fortaleza']

,id,nome,microrregiao,regiao-imediata
58,2304400,Fortaleza,"{'id': 23016, 'nome': 'Fortaleza', 'mesorregia...","{'id': 230001, 'nome': 'Fortaleza', 'regiao-in..."

## webhook (POST)

In [82]:
#site de teste webhook
endpoint = "https://webhook.site/2a8bcf6d-4957-46e0-974f-2a19bab738d6"

data = {
    "nome": "Helena",
    "idade": 50,
    "cidade": "Curitiba"
}

response = requests.post(endpoint, data=data)

In [83]:
response.headers

{'server': 'nginx', 'content-type': 'text/html; charset=UTF-8', 'transfer-encoding': 'chunked', 'x-request-id': '4c805d38-11b9-45a7-a988-ffe56515d8fe', 'x-token-id': '2a8bcf6d-4957-46e0-974f-2a19bab738d6', 'content-security-policy': "signup-to-remove-csp-header 'webhook.site/register'; base-uri 'self'; form-action 'none'; script-src 'none'; worker-src 'none'; frame-src 'none';", 'cache-control': 'no-cache, private', 'date': 'Mon, 20 Apr 2026 10:56:13 GMT'}

In [85]:
response.status_code

200